export const ADD_PANDORA = 'ADD_PANDORA';
export const PANDORA_FAILED = 'PANDORA_FAILED';
export const PANDORA_LOADING = 'PANDORA_LOADING';
export const UPDATE_CURRENT_SONG = 'UPDATE_CURRENT_SONG';
export const CURRENT_SONG_LOADING = 'CURRENT_SONG_LOADING';
export const UPDATE_SONG_RATING = 'UPDATE_SONG_RATING';
export const UPDATE_STATIONS = 'UPDATE_STATIONS';

export const ADD_PLAYER = 'ADD_PLAYER';
export const PLAYER_FAILED = 'PLAYER_FAILED';
export const PLAYER_LOADING = 'PLAYER_LOADING';
export const UPDATE_ISPAUSED = 'UPDATE_PLAYPAUSE';
export const UPDATE_PLAYERRUNNING = 'UPDATE_PLAYERRUNNING';